# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8412dd77faa14bfd64ed236332be49de8c09975bbecd9eed3680d371562f7ed7a6e61dfd8c3d6fb5c093a760ed033943b2a95303c9adc11ca8eafb2757690a36

test:
  secret_key_base: d2774d7553fe8f2f4577700c361f5970dabd9c9f8acfa6732aeae0044931aa68bf934afcff98bbaf5edb541f9ffa4e30fcac76fb33488b0388b7c47ea0c085f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
